server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:9000/oauth2/introspet
          client-id: oauth2-client-app1
          client-secret: secret