server:
    port: 8081

spring:
    security:
        oauth2:
            client:
                registration:
                    springoauth2:
                        clientId: oauth2-client-app1
                        clientSecret: secret1
                        clientName: oauth2-client-app1
                        authorizationGrantType: client_credentials
                        clientAuthenticationMethod: client_secret_basic

                provider:
                    springoauth2:
                        issuerUri: http://localhost:9000
