server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms:
            - RS256
            - RS512
            - HS256
#          public-key-location: classpath:certs/publicKey.txt