server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
#          issuer-uri: http://localhost:8081
          jws-algorithms: RS256
          public-key-location: classpath:certs/publicKey.txt