server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: RS256
#          jws-algorithms: RS512
#          jws-algorithms: HS256
#          public-key-location: classpath:certs/publicKey.txt